# Generated by Django 4.2.3 on 2023-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endorser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorser_name', models.CharField(max_length=20)),
                ('endorser_surname', models.CharField(max_length=20)),
            ],
        ),
    ]
