# Generated by Django 4.2.3 on 2023-08-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endorser',
            old_name='endorser_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='endorser',
            old_name='endorser_surname',
            new_name='surname',
        ),
    ]
